<?php
	session_cache_expire(999999);
	session_start();
	header("Cache-Control: no-store, no-cache, must-revalidate");
	header("Cache-Control: post-check=0, pre-check=0", false);
	header("Pragma: no-cache");
	header('Content-Type: text/html; charset=utf-8');
	$app=isset($_GET["app"]);
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php include 'headCommon.php'; ?>
<?php if($app) { ?>
<meta name="viewport" content="width=600, user-scalable=no, initial-scale=1, minimum-scale=1, maximum-scale=1" />
<?php } ?>
<script type="text/javascript">
//LOCALE, GENERATED BY SERVER
<?php
if($_SESSION["locale"]=="it"){
?>
var <?php if(!$app){ ?>UPLOAD_SUCCESS="Preset caricato",
	UPLOAD_FAIL="Upload fallito",
	UPLOAD_FAIL_CONN="Errore di connessione",
	UPLOAD_FAIL_1="Errore del server",
	UPLOAD_FAIL_2="File preset non valido",
	UPLOAD_FAIL_3="Manca il titolo",
	UPLOAD_FAIL_4="Manca l'autore",
	UPLOAD_FAIL_5="Manca la descrizione",
	<?php } ?>
	DOWNLOAD_TEXT="Download",
	DOWNLOADED="Scaricato",
	DOWNLOADED_TIMES="volte",
	COMMENT_PLACEHOLDER="Scrivi il tuo commento",
	COMMENT_POST="Invia",
	COMMENT_EMPTY="Il commento è vuoto",
	COMMENT_UPLOAD_FAIL="Caricamento del commento fallito, riprova più tardi.",
	COMMENT_LOAD_FAIL="Impossibile caricare i commenti",
	LIST_LOAD_FAIL="Impossibile caricare i preset",
	PRESET_LOAD_FAIL="Impossibile caricare i dettagli",
	UNKNOWN_ERROR="Errore sconosciuto";
<?php
}else{
?>
var <?php if(!$app){ ?> UPLOAD_SUCCESS="Preset uploaded",
	UPLOAD_FAIL="Upload failed",
	UPLOAD_FAIL_CONN="Connection error",
	UPLOAD_FAIL_1="Server error",
	UPLOAD_FAIL_2="Not a valid preset file",
	UPLOAD_FAIL_3="Missing title",
	UPLOAD_FAIL_4="Missing author",
	UPLOAD_FAIL_5="Missing description",
	<?php } ?>
	DOWNLOAD_TEXT="Download",
	DOWNLOADED="Downloaded",
	DOWNLOADED_TIMES="times",
	COMMENT_PLACEHOLDER="Type your comment here",
	COMMENT_POST="Post",
	COMMENT_EMPTY="The comment is empty",
	COMMENT_UPLOAD_FAIL="Failed to post comment. Please try again later",
	COMMENT_LOAD_FAIL="Couldn't load comments",
	LIST_LOAD_FAIL="Failed to load presets",
	PRESET_LOAD_FAIL="Couldn't load preset details",
	UNKNOWN_ERROR="Unknown error";
<?php
}
?>
function cssAnimationSupported(){
	return document.createElement('div').style["animation"]!==undefined;
}
function showLoading(container){
var l=document.createElement("img");
l.className="loading";
if(cssAnimationSupported()) l.src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAB3RJTUUH3gQVCzkNCsfIdAAAAwpJREFUWMO9lzuLFFEQhb/u6R622ufSuy7IGqwoCoosCIJGK6hgJiZiIiYGBiKY+Av0B4ihDxCMRAwUBBMTHxgospjoirKKL7DB13bNaPeMSfVwGcZxnLan4MLQ3XPPqVN1b1V5DGgishrYB8wBs8AMUAOOq+p1hjRvAOCNwEngILAC8LvWfVWdG5ZA0Ac4Ak4Dx4AxA2t3fdYGblPCgj+ArwcuAFsc4DagwF3gIfAceAUslCHg9QDfBlwBJh2ZE+A8cFVVvw4LlqYpURT1jfeMiDwWkUUReSsi70TknIiMU9LSNEVEvDRNeytgMb8GbDavAc4AF1W1XRY8jmO/wEuSJC+UcHPgBLABaFm8zyZJcqmvZANaHMeegXuAF8cxQE7hqYjMAIcNvAVcBy7/D3DzuFCwyKlQRDwcqY/apZIDn4CzZWV3LYoikiTJTYEOCQBfRFYCew08By6UyfR+JGz/IhfqIuIFwE6gbi+bwA2qM1cFgMAHtjveP1DV71WhW1hbbhgCy/zcvnlC9dZywhAGwBogswevR0SgZr/DABBHgS8jINB2CBCY977zsmrzHAJtH/jmJOGKERCo2fIBzwfemwoZMD0CAnWHRMsHXpr3mRWiqi1yCGQ+8NQhsNWqYiUmIjULc0Gg4dvZXzISNWs6q7JxqwE1S8bUV9Ul4J6jwn4RWVaB9wEw5STgD1XNi+N3E2gYieXAoaJc/g+zLmidNbcFgc+dcqyq74E7jgo7gN3d7VOJbmit3bidHlNVm24/gFXBRSPRAg7EcTxXRgkDnwbWO4nXBD707IpFZAo4ZUeluJweAbdUNf3HmIfAJvO8cKoJzKtqw72VOpZl2VIYhi+ArXZNtyxxZsMwzMMw/JxlWfY34DAMZ2x8W+U4+gt41u2I94dNJoEjNhvkTm40bBB5Y7OCWv2o2/mesNV2/pPbdT/fS0Wvjyd1YI8lJM6Gg6zi219W4hdUNR92OJ0AdjnzQjdIL+CmqbSgqj9KTccOkTHL5mmTOXI66RT4amf7I/BBVX8Osu9vSZob3/WKrPUAAAAASUVORK5CYII="; else l.src="images/loadingFallback.gif";
container.innerHTML="";
container.appendChild(l);
}
String.prototype.getValueByKey = function (k) {
    var p = new RegExp('\\b' + k + '\\b', 'gi');
    return this.search(p) != -1 ? decodeURIComponent(this.substr(this.search(p) + k.length + 1).substr(0, this.substr(this.search(p) + k.length + 1).search(/(&|;|$)/))) : "";
};
String.prototype.isBlank=function(){
	return !this || /^\s*$/.test(this);
}
var loaded=false;
function presetUploadComplete(){
	<?php if(!$app){ ?>
	if(!loaded){loaded=true; return;}
	var d=document.getElementById('uploadHelper').contentWindow.document.body.innerHTML;
	try{
		var n=parseInt(d);
		if(n==0) uploadOK(); else uploadFAIL(n);
	}catch(e){
		uploadFAIL(-1);
	}
	enableUploadAndReload();
	<?php } ?>
}
function uploadOK(){
	<?php if(!$app){ ?>
	document.getElementById("uploader").reset();
	loadPresetList();
	alert(UPLOAD_SUCCESS);
	<?php } ?>
}
function uploadFAIL(errno){
	<?php if(!$app){ ?>
	var err="";
	switch(errno){
		case -1: err=UPLOAD_FAIL_CONN; break;
		case 1: err=UPLOAD_FAIL_1; break;
		case 2: err=UPLOAD_FAIL_2; break;
		case 3: err=UPLOAD_FAIL_3; break;
		case 4: err=UPLOAD_FAIL_4; break;
		case 5: err=UPLOAD_FAIL_5; break;
		default: err=UNKNOWN_ERROR;
	}
	alert(UPLOAD_FAIL+": "+err);
	<?php } ?>
}

function disableUploadAndReload(){
	<?php if(!$app){ ?>
		document.getElementById("uploadButton").disabled=true; document.getElementById("reload").style.display="none";
	<?php } ?>
}
function enableUploadAndReload(){
	<?php if(!$app){ ?>
		document.getElementById("uploadButton").disabled=false; document.getElementById("reload").style.display="inline-block";
	<?php } ?>
}

var expandedPresets=new Array();
var urlQuery=location.search.getValueByKey('id');
if(!(urlQuery.isBlank())) expandedPresets.push(urlQuery);
var presetFromQueryShown=false;
function loadPresetList(){
	disableUploadAndReload();
	var xhr=new XMLHttpRequest();
	var l=document.getElementById("presetList");
	showLoading(l);
	xhr.onreadystatechange=function(){
		if(xhr.readyState==4){
			if(xhr.status==200){
				try{
					if(parseInt(xhr.responseText)==1){l.innerHTML=LIST_LOAD_FAIL; enableUploadAndReload(); return;}
				}catch(e){}
				try{
					var presets=xhr.responseXML.documentElement.getElementsByTagName("Preset");
					l.innerHTML="";
					for(var i=0;i<presets.length;i++){
						var e=document.createElement("div");
						e.className="preset";
						var h=document.createElement("div");
						h.className="header";
						var t=document.createElement("div");
						t.innerHTML=presets[i].getElementsByTagName("title")[0].firstChild.nodeValue;
						t.className="title";
						h.appendChild(t);
						t=document.createElement("div");
						t.innerHTML=presets[i].getElementsByTagName("author")[0].firstChild.nodeValue;
						t.className="author";
						h.appendChild(t);
						e.appendChild(h);
						t=document.createElement("div");
						t.className="expansion";
						t.setAttribute("id","exp"+presets[i].getAttribute("id"));
						t.style.display="none";
						e.appendChild(t);
						h.setAttribute("onclick","toggle('"+presets[i].getAttribute("id")+"');");
						l.appendChild(e);
						if(!presetFromQueryShown&&i==urlQuery){
							try{e.scrollIntoView({block: "start", behavior: "smooth"}); presetFromQueryShown=true;}catch(e){} //scroll if supported
						}
					}
				}catch(e){
					l.innerHTML=LIST_LOAD_FAIL;  enableUploadAndReload(); return;
				}
				for(var i=0;i<expandedPresets.length;i++){
					toggle(expandedPresets.shift());
				}
				enableUploadAndReload();
			}
		}
	}
	xhr.open("GET","presetList.php?r="+Math.random(),true);
	xhr.send();
}

function addDownload(id){
	var xhr=new XMLHttpRequest();
	xhr.open("GET","add_download.php?id="+id+"&r="+Math.random(),false);
	xhr.send();
}
function toggle(id){
	try{
		var d=document.getElementById("exp"+id);
		if(d.style.display=="none"){loadExpansionAndShow(id); expandedPresets.push(id); d.parentElement.scrollIntoView({block: "start", behavior: "smooth"});} else {
			d.style.display="none";
			for(var i = expandedPresets.length; i--;) {
				if(expandedPresets[i] === id) {
					expandedPresets.splice(i, 1);
				}
			}
		}
	}catch(e){}
}
function loadExpansionAndShow(id){
	var exp=document.getElementById("exp"+id);
	showLoading(exp);
	exp.style.display="block";
	var xhr=new XMLHttpRequest();
	xhr.onreadystatechange=function(){
		if(xhr.readyState==4){
			if(xhr.status==200){
				try{
					if(parseInt(xhr.responseText)==1){exp.innerHTML=PRESET_LOAD_FAIL; return;}
				}catch(e){}
				try{
					exp.innerHTML="";
					var preset=xhr.responseXML.documentElement.getElementsByTagName("Preset")[0];
					var d=document.createElement("div");
					d.innerHTML=preset.getElementsByTagName("description")[0].firstChild.nodeValue;
					exp.appendChild(d);
					d=document.createElement("div");
					d.className="buttonArea";
					var a=document.createElement("a");
					a.className="download";
					a.innerHTML="Download";
					a.href=preset.getElementsByTagName("url")[0].firstChild.nodeValue;
					a.setAttribute("onclick","addDownload('"+id+"')");
					d.appendChild(a);
					a=document.createElement("span");
					a.className="downloadCount";
					a.innerHTML=DOWNLOADED+" "+preset.getElementsByTagName("downloads")[0].firstChild.nodeValue+" "+DOWNLOADED_TIMES;
					d.appendChild(a);
					<?php if(!$app){ ?>
					a=document.createElement("input");
					a.className="social";
					a.type="text";
					a.setAttribute("readonly","readonly");
					a.setAttribute("onclick","this.select()");
					a.value="http://sine.adolfintel.com/goto.php?id="+id;
					d.appendChild(a);
					a=document.createElement("a");
					a.className="social";
					a.innerHTML="<img src='images/gplus.png' alt='Google+' />";
					a.href="https://plus.google.com/share?url=http://sine.adolfintel.com/goto.php%3Fid="+id;
					a.target="_blank";
					d.appendChild(a);
					a=document.createElement("a");
					a.className="social";
					a.innerHTML="<img src='images/twitter.png' alt='Twitter' />";
					a.href="https://twitter.com/share?url=http://sine.adolfintel.com/goto.php%3Fid="+id;
					a.target="_blank";
					d.appendChild(a);
					a=document.createElement("a");
					a.className="social";
					a.innerHTML="<img src='images/fb.png' alt='Facebook' />";
					a.href="https://www.facebook.com/sharer.php?u=http://sine.adolfintel.com/goto.php%3Fid="+id;
					a.target="_blank";
					d.appendChild(a);
					<?php } ?>
					a=document.createElement("iframe");
					a.src="like.php?id="+id;
					a.seamless="seamless";
					a.style.display="block";
					a.style.width="100%";
					a.style.height= "40px";
					a.style.border="none";
					a.style.overflow="hidden";
					a.style.marginTop="1em";
					a.allowTransparency="true";
					a.frameBorder="0"; //IE8...
					d.appendChild(a);
					a=document.createElement("div");
					a.className="comments";
					createCommentsForm(id,a);
					d.appendChild(a);
					exp.appendChild(d);
				}catch(e){
					exp.innerHTML=PRESET_LOAD_FAIL;
				}
			}
		}
	}
	xhr.open("GET","presetList.php?id="+id+"&full=true&r="+Math.random(),true);
	xhr.send();
}

function createCommentsForm(id,container){
	var f=document.createElement("form");
	var t=document.createElement("textarea");
	t.name="text";
	t.rows=4;
	t.setAttribute("placeholder",COMMENT_PLACEHOLDER);
	f.appendChild(t);
	var b=document.createElement("input");
	b.type="button";
	b.value=COMMENT_POST;
	f.appendChild(b);
	container.appendChild(f);
	var c=document.createElement("div");
	c.className="commentsArea";
	container.appendChild(c);
	b.onclick=function(){sendComment(id,t,c);};
	loadComments(id,c);
}
function loadComments(id,container){
	showLoading(container);
	var xhr=new XMLHttpRequest();
	xhr.onreadystatechange=function(){
		if(xhr.readyState==4){
			if(xhr.status==200){
				try{
					if(parseInt(xhr.responseText)==1){container.innerHTML=COMMENT_LOAD_FAIL; return;}
				}catch(e){}
				try{
					container.innerHTML="";
					var comments=xhr.responseXML.documentElement.getElementsByTagName("comment");
					for(var i=0;i<comments.length;i++){
						var c=document.createElement("div");
						c.className="comment";
						c.innerHTML=comments[i].firstChild.nodeValue;
						container.appendChild(c);
					}
				}catch(e){
					container.innerHTML=COMMENT_LOAD_FAIL;
				}
			}
		}
	}
	xhr.open("GET","getComments.php?id="+id+"&r="+Math.random(),true);
	xhr.send();
}
function sendComment(id,t,commentsArea){
	if(t.value.isBlank()){ alert(COMMENT_EMPTY); return;}
	var text=t.value;
	var xhr=new XMLHttpRequest();
	xhr.onreadystatechange=function(){
		if(xhr.readyState==4){
			if(xhr.status==200){
				try{
					if(parseInt(xhr.responseText)==1){alert(COMMENT_UPLOAD_FAIL); return;}
				}catch(e){alert(COMMENT_UPLOAD_FAIL); return;}
				t.value="";
				loadComments(id,commentsArea);
			}
		}
	}
	var params="";
	params+="id="+encodeURIComponent(id)+"&text="+encodeURIComponent(text)+"&r="+Math.random();
	xhr.open("POST","postComment.php",false);
	xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
	xhr.setRequestHeader("Content-length", params.length);
	xhr.setRequestHeader("Connection", "close");
	xhr.send(params);
}
</script>

<style type="text/css">
<?php if($app){ ?>
	@font-face {
		font-family: 'Roboto';
		font-style: normal;
		font-weight: 400;
		src: local('Roboto Regular'), local('Roboto'), url(fonts/roboto400.woff) format('woff');		
	}
	html{
		font-family: 'Roboto' !important;
		background-color:#FFFFFF;
		font-size:1.1em;
	}
<?php } ?>

#spacer{
<?php if($app){ ?>
	height:0.8em;
<?php } ?>
}
div.preset{
	background-color:#FFFFFF;
	font-weight:400;
	<?php if($app){?>
		width:100%;
		margin-left:auto;
		margin-right:auto;
		border-bottom:1px solid #DDDDDD;
	<?php }else{ ?>
		border:0.08em solid #E0E0E0;
		border-bottom:0.16em solid #DDDDDD;
		border-radius:0.18em;
		margin-bottom:0.6em;
	<?php } ?>
}
div.preset > div.header{
	padding:0.4em;
	cursor: pointer;
	<?php if($app){?>
		padding:0.6em 0.6em 1em 0.6em;
	<?php } ?>
}
div.preset > div.header > div.title{
	font-size:1.1em;
}
div.preset > div.header > div.author{
	font-size:0.85em;
	color:#808080;
}
div.preset > div.expansion{
	background-color:#DDDDDD;
	padding:0.4em;
}
div.preset > div.expansion > div.buttonArea{
	margin-top:0.8em;
}
div.preset > div.expansion > div.buttonArea > a.download{
	text-decoration:underline !important;
}
div.preset > div.expansion > div.buttonArea > span.downloadCount{
	font-size:0.85em;
	color:#808080;
	margin-left:1em;
}
<?php if(!$app){ ?>
#reload{
	cursor:pointer;
}
h1{
	font-size:1.65em;
}
div.preset > div.expansion > div.buttonArea > a.social > img , div.preset > div.expansion > div.buttonArea > input.social{
	display:inline-block;
	height:2em;
	width:auto;
	margin-left:0.15em;
	vertical-align:middle;
	float:right;
}
div.preset > div.expansion > div.buttonArea > input.social{
	width:12em;
}
@media all and (max-width: 35em){
	div.preset > div.expansion > div.buttonArea > a.social > img , div.preset > div.expansion > div.buttonArea > input.social{
		font-size:0.6em;
	}
}
<?php } ?>
div.comments{
	margin-top:1em;
}
div.comments input[type="button"]{
	display:block;
	min-width:8em;
	margin:0.3em 0 0 auto;
}
div.comments > div.commentsArea{
	margin-top:0.5em;
}
div.comments > div.commentsArea > div.comment{
	border-bottom:1px solid #CCCCCC;
	font-size:0.8em;
	margin-bottom:1em;
}
</style>
</head>
<body onload="loadPresetList();" <?php if($_SESSION["locale"]=="it") echo "lang='it'"; else echo "lang='en'";?>>
<?php if(!$app){ ?>
<div class="wrapper">
<div class="wrapper">
<?php } ?>
<?php if(!$app) include 'header.php'; ?>
<div <?php if(!$app) echo "class='content'"?>>
<?php if(!$app){ ?>
<div>
<h1><?php if($_SESSION["locale"]=="it") echo "Carica preset"; else echo "Upload preset";?></h1>
<iframe id="uploadHelper" name="uploadHelper" style="display:none" onload="presetUploadComplete()"></iframe>
<form id="uploader" action="uploader.php" method="post" enctype="multipart/form-data" target="uploadHelper" >
	<input name="mFile" id="mFile" type="file" />
	<input type="button" id="uploadButton" value="Upload" onclick="if(!(document.getElementById('mFile').value.isBlank())){ disableUploadAndReload(); submit();}"/> 
</form>
</div>
<?php } ?>
<?php if(!$app){ ?>
<h1><?php if($_SESSION["locale"]=="it") echo "Preset"; else echo "Presets";?> <img id="reload" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAA7CAAAOwgEVKEqAAAAAB3RJTUUH3gQVDyYJx/mqLwAAAahJREFUOMuV082LTmEcxvHP8zLj5yX3M2qI8tZMGcSCvKQUpWRiIWuzGbPzF5CsLWQWrJTY2MnG0oJZSSwsZGMhM8JEumvSHGYmC/cznZ5IrroXp1/f6/zOfV2noUcppSEcwAlsQz8+YwrP8TLnvJBS2oSLjRrYhzO4jF2IHu9FzOAuHuAajjcKHLiOcawowDxmsYB16NTMltCEdkqpiTFMoK8Mn2ES72sG53EOq7owtHEIl2rwFUzmnL+X7RrYjoHadstqYhSby/NUHS46jDs4jVavQRtni9EcbvTA8AIXsA87sQfrsRGD7bKeEtVM7xtyzj/xthwppf5yJ8sG7VpMi/6hnPMPfCpHEx/KbLCs9l9qRcQwDmIlIiIeVlW19DcgpTQWEbciYiQiGq2IWMJJrMYw3kXE6z+ZpJRGcBt7cQTTrYiYLn0/Vu5jFLsj4mv8VicihiJiAjdrkT/G1W6VO7hXsu627As+liYOYEttNlP+m1ctqKpqPiIeFWgH1mINNpS4OmjgG+5jPOf8pqoqjZ5vbGI/juIUtpaKz5aWPsHTnPNcl/kF8Epxr+gmFjQAAAAASUVORK5CYII=" alt="Refresh" onclick="loadPresetList()"/></h1>
<?php } ?>
<div id="spacer"></div>
<div id="presetList"></div>
</div>
<?php if(!$app) include 'footer.php'; ?>
<?php if(!$app){ ?>
</div>
</div>
<?php } ?>
</body>
</html>
